services:
  web:
    extends:
      file: ../docker-compose.common.yml
      service: mastodon
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    restart: always
  streaming:
    extends:
      file: ../docker-compose.common.yml
      service: mastodon
    command: yarn start
    tty: true
    restart: always
  sidekiq:
    extends:
      file: ../docker-compose.common.yml
      service: mastodon
    environment:
      DB_POOL: 30
    command: sh -c "bundle exec sidekiq -c $${DB_POOL}"
    tty: true
    restart: always
