services:
  caddy:
    image: kyori/caddy-realip:latest
    tty: true
    restart: always
  caddy-common:
    extends:
      service: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      APP_HOST: example.com
      CERT_NAME: example.com
      REVERSE_TO: app:3000
  caddy-mastodon:
    extends:
      service: caddy
    volumes:
      - ./Caddyfile.mastodon:/etc/caddy/Caddyfile:ro
    environment:
      MASTODON_DOMAIN: example.com

  cloudflared:
    image: msnelling/cloudflared:2021.9.0
    tty: true
    restart: always

  mastodon-backup:
    image: kyori/docker-mastodon-backup:psql-13.3-redis-5.0.7
    tty: true
    restart: always

  wol-proxy:
    image: ytsurui/wol-on-web:1.0.0
    network_mode: host
    tty: true
    restart: always

  prometheus:
    image: prom/prometheus:v2.25.0
    volumes:
      - /var/lib/prometheus:/prometheus
    tty: true
    restart: always
  alertmanager:
    image: prom/alertmanager:v0.20.0
    volumes:
      - /var/lib/alertmanager:/alertmanager
    tty: true
    restart: always
  alertmanager-discord:
    image: maxsuelmarinho/alertmanager-discord:latest
    tty: true
    restart: always
  node-exporter:
    image: prom/node-exporter:v1.1.2
    volumes:
      - '/:/host:ro,rslave'
    pid: host
    command: --path.rootfs=/host
    tty: true
    restart: always
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.18.0
    volumes:
      - ./blackbox_exporter.yml:/etc/blackbox_exporter/config.yml:ro
    tty: true
    restart: always
  statsd-exporter:
    image: prom/statsd-exporter:v0.20.0
    volumes:
      - ./mastodon-statsd-mapping.yml:/etc/statsd_exporter/mapping.yml:ro
    command: --statsd.mapping-config=/etc/statsd_exporter/mapping.yml
    tty: true
    restart: always
  grafana:
    image: grafana/grafana:7.4.3
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    tty: true
    restart: always

  mysql:
    image: mariadb:10.5
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
    tty: true
    restart: always

  mirakurun:
    image: chinachu/mirakurun:latest
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    devices:
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
      - /dev/bus/usb/:/dev/bus/usb/
    volumes:
      - /usr/local/lib/libarib25.so.0:/usr/local/lib/libarib25.so.0
      - /usr/local/bin/recpt1:/usr/local/bin/recpt1
      - /var/run/:/var/run/
      - /var/lib/mirakurun/data:/app-data
    environment:
      TZ: Asia/Tokyo
    command: /bin/bash -c "ldconfig && ./docker/container-init.sh"
    tty: true
    restart: always
  epgstation:
    image: kyori/epgstation:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/:/var/run/
      - /var/lib/epgstation:/app/data
      - /var/log/epgstation:/app/logs
    environment:
      TZ: Asia/Tokyo
    tty: true
    restart: always
  lemokon:
    image: kyori/lemokon:latest-epgstation-discord
    volumes:
      - /etc/localtime:/etc/localtime:ro
    tty: true
    restart: always

  softether:
    image: siomiz/softethervpn:4.38
    cap_add:
      - NET_ADMIN
    tty: true
    restart: always
  softether-client:
    image: kyori/softether-vpn-client:v4.38-9760-rtm
    cap_add:
      - NET_ADMIN
    tty: true
    restart: always
